// Generated by agentic; source: extensions/opencode/plugins/sound-notification.ts; repository: https://github.com/sawrus/agent-guides
// Generated by agentic; source: extensions/opencode/plugins/sound-notification.ts; repository: https://github.com/sawrus/agent-guides
import type { Plugin } from "@opencode-ai/plugin"

export const SoundNotificationPlugin: Plugin = async ({ $ }) => {
  return {
    event: async ({ event }) => {
      if (event.type === "session.idle") {
        try {
          const platform = process.platform
          if (platform === "darwin") {
            await $`afplay /System/Library/Sounds/Glass.aiff`
          } else if (platform === "linux") {
            try {
              await $`paplay /usr/share/sounds/freedesktop/stereo/complete.oga`
            } catch {
              try {
                await $`aplay /usr/share/sounds/alsa/Front_Center.wav`
              } catch {
                try {
                  await $`pw-play /usr/share/sounds/freedesktop/stereo/complete.oga`
                } catch {}
              }
            }
          }
        } catch {}
      }
    },
  }
}
